site_name: CribSense - a contactless, video-based baby monitor
repo_url: https://github.com/lukehsiao/CribSense
pages:
- Home: 'index.md'
- Software Setup Instructions: 'setup/sw-setup.md'
- Hardware Setup Instructions: 'setup/hw-setup.md'
- Software Configuration Parameters: 'setup/config.md'
- Troubleshooting: 'setup/troubleshooting.md'
theme: readthedocs
